### ISSUE TITLE
What the shortcut key on Linux?

### ISSUE THREAD

**Issue by scottchiefbaker** [pdudits/firefox-supergenpass#1]
The documentation mentions that the shortcut key on Windows is `SHIFT` + `F10`, but declines to mention what the key combo on other OSes is. What is the key?

**Comment by pdudits** [comment]
Hi, thanks for your interest. Per [this thread](https://askubuntu.com/questions/167088/keyboard-shortcut-equivalent-to-right-clicking), it is usually `Shift+F10` as well (and likely `Ctrl+Space` on Mac) , but it might be whatever you bind  your `Menu` keycode to.

**Comment by scottchiefbaker** [comment]
Oh `Shift` + `F10` pulls up the menu... I was expecting it to invoke SGP. Is there a way to bind a key combination to SGP specifically?
